############# English navigation ##############

# main menu

[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Features"
url = "#feature"
weight = 2

[[main]]
name = "Pricing"
url = "#pricing"
weight = 3

[[main]]
name = "Contact"
url = "#contact"
weight = 4


# footer menu

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3

[[footer]]
name = "Terms & Conditions"
url = "/terms-conditions"
weight = 4

# company menu
[[company]]
name = "Home"
url = "/"

#[[company]]
#name = "Product Features"
#url = "/feature/"
#
#[[company]]
#name = "Changelog"
#url = "/changelog/"
#
#[[company]]
#name = "Contact"
#url = "/contact/"

# product menu
[[product]]
name = "Product Features"
url = "#feature"

#[[product]]
#name = "Product Features"
#url = "/feature/"
#
#[[product]]
#name = "Integration"
#url = "/integration/"
#
#[[product]]
#name = "Integration Details"
#url = "/integration/kickstarter/"

# resources menu
[[resources]]
name = "Pricing & Plans"
url = "#pricing"

#[[resources]]
#name = "Blog Details"
#url = "/blog/post-1/"
#
#[[resources]]
#name = "Changelog"
#url = "/changelog/"

# contacts menu
[[contacts]]
name = "Contact Us"
url = "#contact"

#[[services]]
#name = "Book A Demo"
#url = "/"
#
#[[services]]
#name = "404"
#url = "/404/"
